[package]
name = "rusted_wumpus"
version = "0.1.0"
edition = "2021"
readme = "README.md"
authors = ["BuyMyMojo <https://github.com/BuyMyMojo>"]
repository = "https://github.com/BuyMyMojo/Rusted-Wumpus"
license-file = "LICENSE"
keywords = ["discord", "bot"]
description = "A general discord bot made in rust as a learning experince"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.16.1", features = ["full"] }
serenity = { default-features = false, features = ["client", "gateway", "model", "rustls_backend", "standard_framework", "collector", "framework", "cache"], version = "0.10.10"}
owoify = "0.1.5"
dflake = "0.1.0"
chrono = "0.4.19"
rustflake = "0.1.1"