name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Windows Building
      run: rustup target add x86_64-pc-windows-gnu
    - name: install target
      run: rustup toolchain install stable-x86_64-pc-windows-gnu
      
    - name: Build Debug
      run: cargo build --target x86_64-pc-windows-gnu --verbose
    - uses: actions/upload-artifact@v2
      with:
        name: debug-build
        path: target/debug
        
    - name: Build Release
      run: cargo build --target x86_64-pc-windows-gnu --release --verbose
    - uses: actions/upload-artifact@v2
      with:
        name: release-build
        path: target/release
    
