name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz
          - target: x86_64-apple-darwin
            archive: zip
    env:
      CARGO_TERM_COLOR: always
      BUILD_TARGET: ${{ matrix.target }}
      BINARY_NAME: rusted-wumpus
    steps:
    - uses: actions/checkout@v2
    - name: Build-musl
      uses: gmiam/rust-musl-action@master
      with:
        args: cargo build --target  ${{ matrix.target }} --release
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.BINARY_NAME }}-${{ matrix.target }}
        path: target/ ${{ matrix.target }}/release/${{ env.BINARY_NAME }}*
